### ISSUE TITLE
Apex intensities reported as -1.0 on Linux (Ubuntu) using RAW files as input

### ISSUE THREAD

**Issue by jgriss** [compomics/moFF#15]
Hi!

I processed some of the CPTAC study 6 files changing from the mzML input I used previously to the original RAW files.

For some reason, all intensities are now reported as "-1.0". Here's the result and the log file:
[mam_050108o_CPTAC_study6_6C008_080505040419.zip](https://github.com/compomics/moFF/files/1098991/mam_050108o_CPTAC_study6_6C008_080505040419.zip)

Any idea why this is happening?

Thanks for the help!

Best regards,
Johannes

**Comment by Maux82** [comment]
Hi, 

Which of kind of input are you using ? 
The search result of the PeptideShaker that I provided or the result of your search engines ? 
With the same input and mzML file do you get result ?

One possible reason could be that the RT in input file is in  second , but iin RAW file must be in minutes  maybe you comment the line where I do the transformation . This  happens to me a lot if I use different input from different sources like MaxQuant or PeptideShaker

Anyhow, I will take a deep look into this .

**Comment by jgriss** [comment]
Hi,

The input file is from my own pipeline and it works with mzML as input files.

Do I have to convert the RT from seconds into minutes? In your docs I thought it said that your tools expect RT to be in seconds.

About the code: I didn't change anything apart from the code I sent you.

Thanks for your help!

Best regards,
Johannes

**Comment by Maux82** [comment]
No the Rt in seconds is correct , inside the code it  has converted in minute because thermo raw file store in such a way.

What the log file say for each peptide ?
 
Can you print for me args_txic in moff.py ?  like a log.critical(args_txic) before the subprocess call [here]( https://github.com/compomics/moFF/blob/master/moff.py#L296-L298)


However, I have update the master branch with a speedup improvement  regadring the mzML reading( thanks to @mafreitas #14 ) ,  I will appreciate if you can test it, maybe this new version could fix also your problem with the rawfile.
I have tested on a raw file and I did not have any problems.

Andrea
