### ISSUE TITLE
multiple raw/mzML files from one sample

### ISSUE THREAD

**Issue by yafeng** [compomics/moFF#42]
Hi, 
when there are multiple raw/mzML files from one sample, how does the match-between-run mode work?
Will moFF consider each mzML file as one sample?  or how do i tell moFF to consider these multiple mzML files are from one sample. I did n't find in the Readme for this situation.

**Comment by Maux82** [comment]
Hi,
yes, moFF considers each raw file as  a sample, of course a 'sample' can be also a techical replicate of the same biological  setting  (i.e let say 5 different  biological  samples  A-B-C-D-E and 3 replicates for each , in total a matching-between-run (mbr)  with 15 raw files ). If I understand the question,  there is no way to tell any sort weight across runs in the mbr.  Maybe if you if you give me an example case where you need this particolar setting I can answer better the question.

**Comment by yafeng** [comment]
Hi, 
I am not talking about technical replicates.
when peptide pre-fractionation methods are used, one sample usually consists of multiple raw files from different fractions collected in pre-fractionation step.  Say we collect 6 fractions for each sample and it will produce 6 raw files after LC-MS/MS analysis. 

For 10 samples, there will be 10x6 = 60 raw files generated. In maxQuant, it allows users to set the 6 different fractions as 1 experiement and the output will output quantiative values for 10 experiments (corresponding to 10 samples).  

If I use moFF, how does it output MS1 quant values? one for each raw file ?

**Comment by Maux82** [comment]
Hi,
In moFF , you cannot  set all the 6 different  fraction as one experiments. The mbr works for all the comparison between the input sample, so in your case (fractionated samples 6 fractions, 10 samples ) for all the 60 raws  it won 't works. I couldtry to implement this this features in the updates.

But you can try to run moFF with mbr for each fraction for all the sample (10 file at time for 6 times). In this case the mbr will work because across samples the same fraction should have enough shared peptides to train the model. I never tried but it should work.

**Comment by yafeng** [comment]
I see, thanks for explaination!
