### ISSUE TITLE
"lwhm" or "rwhm" equal -1

### ISSUE THREAD

**Issue by fcyu** [compomics/moFF#6]
In my results, some of the "lwhm" or "rwhm" equal -1. What is the meaning of this?

Thanks

**Comment by Maux82** [comment]
This could happened because the XiC data retrieved is not big enough to find the lwhm (left width half maximum) or the rwhm_ (right width half maximum). When this happen of those values  get -1.
You can increase the --rt_w  values to see if you can avoid this. if both value (lwhm,rwhm) are -1 means that moFF was able to extract the XiC and so you should filtered out those point for your further analysis.

**Comment by fcyu** [comment]
Thanks for your reply. I found that in those entries whose lwhm or/and rwhm equal -1, there are still positive values for intensity. I wonder that how the intensity can still be calculated if the program fails to get the lwhm or rwhm?

Thanks

**Comment by Maux82** [comment]
This could happen when an intensity is found but the search of the lwhm or rwhm finds the end of the XiC points extracted.   If you still have problems please send you data that I will inspect  my code on  your data.
